name: Installing Python

on:
  push:
    branches: [ main ] # တွန်းတင်လိုက်သောအခါ main branch ကိုသာ လုပ်ဆောင်ရန်
  workflow_dispatch:
    # လက်ဖြင့် စတင်ရန် ခွင့်ပြုသည်

jobs:
  build:
    strategy:
      matrix:
        # os key ဖြင့် မတူညီသော OS များကို သတ်မှတ်သည်
        os: [ ubuntu-latest, macos-14, windows-latest ]
        # py-version key ဖြင့် Python ဗားရှင်းများကို သတ်မှတ်သည်
        py-version: [ '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os}} # matrix.os တန်ဖိုးကို အသုံးပြုသည်
    steps:
    - name: Checkout repository
      # repository မှ ကုဒ်များကို ရယူသည်
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.py-version }} # matrix.py-version တန်ဖိုးကို ပြသသည်
      # မက်ထရစ်မှ သတ်မှတ်ထားသော Python ဗားရှင်းကို တည်ဆင်သည်
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-version }} # matrix.py-version တန်ဖိုးကို ထည့်သွင်းသည်
        # pip dependencies များကို မြန်နှုန်းမြှင့်တင်ရန် cache လုပ်သည် (ဖိုင်မရှိသဖြင့် ဖယ်ရှားလိုက်သည်)f